version: '3.8'

services:
 app:
    image: ad1740/node:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
       - .:/usr/src/app  # Mount the current directory into the container
       - /usr/src/app/node_modules  # Prevent overwriting the node_modules directory
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - my_overlay_network

networks:
  my_overlay_network:
    external: true  # Assuming you're using an external overlay network
