version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:2000"  # Map host port 3000 to container port 3000
    environment:
      - NODE_ENV=development  # Set the environment to development
    volumes:
      - .:/usr/src/app  # Mount the current directory into the container
      - /usr/src/app/node_modules  # Prevent overwriting the node_modules directory
    restart: always  # Restart the container automatically if it stops
